### ISSUE TITLE
Wrong line number in code analysis

### ISSUE THREAD

**Issue by adaniello** [ptraceur/f3-falsum#10]
Hi,
as you can see also in your screenshot, there's a little issue about line number: if error stack reports a line number (eg. 2032 as in your screenshot, and this number is correct), code analysis highlight previous line (eg 2031 in your screenshot).
Indeed line numbers in code analysis is -1.

Thanks

**Comment by ptraceur** [comment]
I see, you're right. I'll correct this as soon as possible, thanks ;)

**Comment by ptraceur** [comment]
Hi, I got some time to solve this:
https://github.com/ptraceur/f3-falsum/commit/8d9fab3a8273b64e00465c2156a5a42780e5df8d

version 2.5 is correct ;)

Cheers

**Comment by adaniello** [comment]
Sorry, but as i reported the error stack returns the right line number. Code analysis has the issue, by reporting line number -1.

Your fix changes the line number in error stack, but this is right.

;P
